lane_detector:
  ros__parameters:
    camera_topic: "/zed/rgb/image_rect_color"
    camera_info_topic: "/zed/rgb/camera_info"

lane_follower:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    drive_topic: "/vesc/high_level/input/nav_2"

race_safety_controller:
  ros__parameters:
    scan_topic: "/scan"
    drive_topic: "/vesc/low_level/input/safety"
    nav_topic: "/vesc/input/navigation"
